version: "3.8"
services:
  # client
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: sh -c "npm run dev"
    env_file:
      - .env
  # server
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./server/:/app/
    depends_on:
      - db
  # database
  db:
    image: postgres:16
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  # pg-admin
  pgadmin4:
    image: elestio/pgadmin
    restart: always
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=1000
    ports:
      - 1000:1000
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
