import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Providers } from "./providers";
import "@/styles/globals.css";
import Navigation from "@/components/navbar/Navbar";
import ThemeProvider from "providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="text-foreground bg-background min-h-[100dvh]">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
