import sqlmodel
"""form is public field

Revision ID: 4519945eab3b
Revises: 48f44d93d47e
Create Date: 2024-03-27 17:21:49.387468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4519945eab3b'
down_revision: Union[str, None] = '48f44d93d47e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form', 'is_public')
    # ### end Alembic commands ###
