import sqlmodel

"""add form_type column

Revision ID: 4b4df39f15e6
Revises: 6c8cccd5a210
Create Date: 2024-05-02 12:24:22.997095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b4df39f15e6"
down_revision: Union[str, None] = "6c8cccd5a210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form",
        sa.Column(
            "form_type", sa.Enum("campaign", "flow", name="formtype"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form", "form_type")
    # ### end Alembic commands ###
