import sqlmodel

"""add first n last name to users

Revision ID: 9bf258dfeea0
Revises: 4519945eab3b
Create Date: 2024-04-07 19:04:14.534523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bf258dfeea0"
down_revision: Union[str, None] = "4519945eab3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("firstname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user", sa.Column("lastname", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_column("user", "lastname")
    op.drop_column("user", "firstname")
    # ### end Alembic commands ###
